export const FIGHTERS = [
  {
    name: 'Mario',
    number: 1,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Donkey Kong',
    number: 2,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Link',
    number: 3,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Samus',
    number: 4,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Dark Samus',
    number: 4,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Yoshi',
    number: 5,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Kirby',
    number: 6,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Fox',
    number: 7,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pikachu',
    number: 8,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Luigi',
    number: 9,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ness',
    number: 10,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Captain Falcon',
    number: 11,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Jigglypuff',
    number: 12,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Peach',
    number: 13,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Daisy',
    number: 13,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Bowser',
    number: 14,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ice Climbers',
    number: 15,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Sheik',
    number: 16,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Zelda',
    number: 17,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Dr. Mario',
    number: 18,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pichu',
    number: 19,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Falco',
    number: 20,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Marth',
    number: 21,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Lucina',
    number: 21,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Young Link',
    number: 22,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ganondorf',
    number: 23,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Mewtwo',
    number: 24,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Roy',
    number: 25,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Chrom',
    number: 25,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Mr. Game & Watch',
    number: 26,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Meta Knight',
    number: 27,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pit',
    number: 28,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Dark Pit',
    number: 28,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Zero Suit Samus',
    number: 29,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Wario',
    number: 30,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Snake',
    number: 31,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ike',
    number: 32,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pokémon Trainer',
    number: 33,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pokémon Trainer',
    number: 34,
    echo: false,
    pickable: false,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pokémon Trainer',
    number: 35,
    echo: false,
    pickable: false,
    dlc: false,
    alts: [],
  },
  {
    name: 'Diddy Kong',
    number: 36,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Lucas',
    number: 37,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Sonic',
    number: 38,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'King Dedede',
    number: 39,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Olimar',
    number: 40,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Lucario',
    number: 41,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'R.O.B.',
    number: 42,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Toon Link',
    number: 43,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Wolf',
    number: 44,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Villager',
    number: 45,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Mega Man',
    number: 46,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Wii Fit Trainer',
    number: 47,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Rosalina & Luma',
    number: 48,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Little Mac',
    number: 49,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Greninja',
    number: 50,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Mii Brawler',
    number: 51,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Mii Swordfighter',
    number: 52,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Mii Gunner',
    number: 53,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Palutena',
    number: 54,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pac-Man',
    number: 55,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Robin',
    number: 56,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Shulk',
    number: 57,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Bowser Jr.',
    number: 58,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Duck Hunt',
    number: 59,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ryu',
    number: 60,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ken',
    number: 60,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Cloud',
    number: 61,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Corrin',
    number: 62,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Bayonetta',
    number: 63,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Inkling',
    number: 64,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ridley',
    number: 65,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Simon',
    number: 66,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Richter',
    number: 66,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'King K. Rool',
    number: 67,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Isabelle',
    number: 68,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Incineroar',
    number: 69,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Piranha Plant',
    number: 70,
    echo: false,
    pickable: true,
    dlc: true,
    alts: [],
  },
  {
    name: 'Joker',
    number: 71,
    echo: false,
    pickable: true,
    dlc: true,
    alts: [],
  },
];
