export const FIGHTERS = [
  {
    name: 'Mario',
    number: 1,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 390,
      offsetX: 0,
      offsetY: -30,
    },
  },
  {
    name: 'Donkey Kong',
    number: 2,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 400,
      offsetX: -40,
      offsetY: 0,
    },
  },
  {
    name: 'Link',
    number: 3,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 570,
      offsetX: -130,
      offsetY: -40,
    },
  },
  {
    name: 'Samus',
    number: 4,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 530,
      offsetX: -60,
      offsetY: -13,
    },
  },
  {
    name: 'Dark Samus',
    number: 4,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 520,
      offsetX: -120,
      offsetY: -3,
    },
  },
  {
    name: 'Yoshi',
    number: 5,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 360,
      offsetX: -20,
      offsetY: 5,
    },
  },
  {
    name: 'Kirby',
    number: 6,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 320,
      offsetX: -4,
      offsetY: 4,
    },
  },
  {
    name: 'Fox',
    number: 7,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 530,
      offsetX: -60,
      offsetY: 0,
    },
  },
  {
    name: 'Pikachu',
    number: 8,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 350,
      offsetX: 0,
      offsetY: -15,
    },
  },
  {
    name: 'Luigi',
    number: 9,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 420,
      offsetX: 0,
      offsetY: 0,
    },
  },
  {
    name: 'Ness',
    number: 10,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 330,
      offsetX: 0,
      offsetY: 0,
    },
  },
  {
    name: 'Captain Falcon',
    number: 11,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 700,
      offsetX: -70,
      offsetY: 0,
    },
  },
  {
    name: 'Jigglypuff',
    number: 12,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 340,
      offsetX: 3,
      offsetY: 0,
    },
  },
  {
    name: 'Peach',
    number: 13,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 680,
      offsetX: -170,
      offsetY: -60,
    },
  },
  {
    name: 'Daisy',
    number: 13,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 650,
      offsetX: -110,
      offsetY: -40,
    },
  },
  {
    name: 'Bowser',
    number: 14,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 490,
      offsetX: -150,
      offsetY: -100,
    },
  },
  {
    name: 'Ice Climbers',
    number: 15,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 400,
      offsetX: -30,
      offsetY: -80,
    },
  },
  {
    name: 'Sheik',
    number: 16,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 600,
      offsetX: -100,
      offsetY: 0,
    },
  },
  {
    name: 'Zelda',
    number: 17,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 820,
      offsetX: -210,
      offsetY: 0,
    },
  },
  {
    name: 'Dr. Mario',
    number: 18,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 480,
      offsetX: -70,
      offsetY: 0,
    },
  },
  {
    name: 'Pichu',
    number: 19,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 370,
      offsetX: -30,
      offsetY: 0,
    },
  },
  {
    name: 'Falco',
    number: 20,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 530,
      offsetX: -50,
      offsetY: -30,
    },
  },
  {
    name: 'Marth',
    number: 21,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 800,
      offsetX: -250,
      offsetY: -10,
    },
  },
  {
    name: 'Lucina',
    number: 21,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 800,
      offsetX: -250,
      offsetY: 10,
    },
  },
  {
    name: 'Young Link',
    number: 22,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 600,
      offsetX: -190,
      offsetY: -50,
    },
  },
  {
    name: 'Ganondorf',
    number: 23,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 750,
      offsetX: -180,
      offsetY: 0,
    },
  },
  {
    name: 'Mewtwo',
    number: 24,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 600,
      offsetX: -170,
      offsetY: 0,
    },
  },
  {
    name: 'Roy',
    number: 25,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 800,
      offsetX: -150,
      offsetY: -50,
    },
  },
  {
    name: 'Chrom',
    number: 25,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 800,
      offsetX: -200,
      offsetY: -50,
    },
  },
  {
    name: 'Mr. Game & Watch',
    number: 26,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 360,
      offsetX: 0,
      offsetY: -25,
    },
  },
  {
    name: 'Meta Knight',
    number: 27,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 450,
      offsetX: -70,
      offsetY: -70,
    },
  },
  {
    name: 'Pit',
    number: 28,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 750,
      offsetX: -150,
      offsetY: -50,
    },
  },
  {
    name: 'Dark Pit',
    number: 28,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 750,
      offsetX: -250,
      offsetY: -70,
    },
  },
  {
    name: 'Zero Suit Samus',
    number: 29,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 800,
      offsetX: -200,
      offsetY: 20,
    },
  },
  {
    name: 'Wario',
    number: 30,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 450,
      offsetX: -50,
      offsetY: 0,
    },
  },
  {
    name: 'Snake',
    number: 31,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 700,
      offsetX: -200,
      offsetY: 0,
    },
  },
  {
    name: 'Ike',
    number: 32,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 800,
      offsetX: -160,
      offsetY: 0,
    },
  },
  {
    name: 'Pokémon Trainer',
    number: 33,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 700,
      offsetX: -180,
      offsetY: 0,
    },
  },
  {
    name: 'Pokémon Trainer',
    number: 34,
    echo: false,
    pickable: false,
    dlc: false,
    alts: [],
    display: {
      scale: 320,
      offsetX: 0,
      offsetY: 0,
    },
  },
  {
    name: 'Pokémon Trainer',
    number: 35,
    echo: false,
    pickable: false,
    dlc: false,
    alts: [],
    display: {
      scale: 320,
      offsetX: 0,
      offsetY: 0,
    },
  },
  {
    name: 'Diddy Kong',
    number: 36,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 360,
      offsetX: -20,
      offsetY: 0,
    },
  },
  {
    name: 'Lucas',
    number: 37,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 380,
      offsetX: -50,
      offsetY: 0,
    },
  },
  {
    name: 'Sonic',
    number: 38,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 360,
      offsetX: -10,
      offsetY: 0,
    },
  },
  {
    name: 'King Dedede',
    number: 39,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 400,
      offsetX: -30,
      offsetY: 0,
    },
  },
  {
    name: 'Olimar',
    number: 40,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 380,
      offsetX: -20,
      offsetY: -10,
    },
  },
  {
    name: 'Lucario',
    number: 41,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 420,
      offsetX: -30,
      offsetY: -10,
    },
  },
  {
    name: 'R.O.B.',
    number: 42,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 480,
      offsetX: -130,
      offsetY: 20,
    },
  },
  {
    name: 'Toon Link',
    number: 43,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 360,
      offsetX: 0,
      offsetY: -20,
    },
  },
  {
    name: 'Wolf',
    number: 44,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 520,
      offsetX: -100,
      offsetY: 0,
    },
  },
  {
    name: 'Villager',
    number: 45,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 400,
      offsetX: -40,
      offsetY: -50,
    },
  },
  {
    name: 'Mega Man',
    number: 46,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 400,
      offsetX: -20,
      offsetY: 0,
    },
  },
  {
    name: 'Wii Fit Trainer',
    number: 47,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 800,
      offsetX: -200,
      offsetY: 0,
    },
  },
  {
    name: 'Rosalina & Luma',
    number: 48,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 500,
      offsetX: -60,
      offsetY: 0,
    },
  },
  {
    name: 'Little Mac',
    number: 49,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 500,
      offsetX: -25,
      offsetY: 0,
    },
  },
  {
    name: 'Greninja',
    number: 50,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 500,
      offsetX: -80,
      offsetY: 0,
    },
  },
  {
    name: 'Mii Brawler',
    number: 51,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 550,
      offsetX: -110,
      offsetY: -10,
    },
  },
  {
    name: 'Mii Swordfighter',
    number: 52,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 430,
      offsetX: -70,
      offsetY: -10,
    },
  },
  {
    name: 'Mii Gunner',
    number: 53,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 430,
      offsetX: -30,
      offsetY: -10,
    },
  },
  {
    name: 'Palutena',
    number: 54,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 800,
      offsetX: -220,
      offsetY: -30,
    },
  },
  {
    name: 'Pac-Man',
    number: 55,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 400,
      offsetX: -20,
      offsetY: 0,
    },
  },
  {
    name: 'Robin',
    number: 56,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 800,
      offsetX: -210,
      offsetY: -30,
    },
  },
  {
    name: 'Shulk',
    number: 57,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 700,
      offsetX: -100,
      offsetY: -100,
    },
  },
  {
    name: 'Bowser Jr.',
    number: 58,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 460,
      offsetX: -80,
      offsetY: -100,
    },
  },
  {
    name: 'Duck Hunt',
    number: 59,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 320,
      offsetX: 0,
      offsetY: -70,
    },
  },
  {
    name: 'Ryu',
    number: 60,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 800,
      offsetX: -240,
      offsetY: 0,
    },
  },
  {
    name: 'Ken',
    number: 60,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 600,
      offsetX: -190,
      offsetY: 0,
    },
  },
  {
    name: 'Cloud',
    number: 61,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 800,
      offsetX: -150,
      offsetY: -30,
    },
  },
  {
    name: 'Corrin',
    number: 62,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 800,
      offsetX: -270,
      offsetY: 0,
    },
  },
  {
    name: 'Bayonetta',
    number: 63,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 800,
      offsetX: -210,
      offsetY: -40,
    },
  },
  {
    name: 'Inkling',
    number: 64,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 430,
      offsetX: -40,
      offsetY: -70,
    },
  },
  {
    name: 'Ridley',
    number: 65,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 500,
      offsetX: -10,
      offsetY: -40,
    },
  },
  {
    name: 'Simon',
    number: 66,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 750,
      offsetX: -160,
      offsetY: -30,
    },
  },
  {
    name: 'Richter',
    number: 66,
    echo: true,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 750,
      offsetX: -160,
      offsetY: -80,
    },
  },
  {
    name: 'King K. Rool',
    number: 67,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 480,
      offsetX: -70,
      offsetY: 0,
    },
  },
  {
    name: 'Isabelle',
    number: 68,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 500,
      offsetX: -80,
      offsetY: -100,
    },
  },
  {
    name: 'Incineroar',
    number: 69,
    echo: false,
    pickable: true,
    dlc: false,
    alts: [],
    display: {
      scale: 530,
      offsetX: 0,
      offsetY: 0,
    },
  },
  {
    name: 'Piranha Plant',
    number: 70,
    echo: false,
    pickable: true,
    dlc: true,
    alts: [],
    display: {
      scale: 320,
      offsetX: 0,
      offsetY: 10,
    },
  },
  {
    name: 'Joker',
    number: 71,
    echo: false,
    pickable: true,
    dlc: true,
    alts: [],
    display: {
      scale: 740,
      offsetX: -180,
      offsetY: 0,
    },
  },
];
