export const FIGHTERS = [
  {
    name: 'Mario',
    number: '01',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Donkey Kong',
    number: '02',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Link',
    number: '03',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Samus',
    number: '04',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Dark Samus',
    number: '04e',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Yoshi',
    number: '05',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Kirby',
    number: '06',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Fox',
    number: '07',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pikachu',
    number: '08',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Luigi',
    number: '09',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ness',
    number: '10',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Captain Falcon',
    number: '11',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Jigglypuff',
    number: '12',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Peach',
    number: '13',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Daisy',
    number: '13e',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Bowser',
    number: '14',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ice Climbers',
    number: '15',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Sheik',
    number: '16',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Zelda',
    number: '17',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Dr. Mario',
    number: '18',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pichu',
    number: '19',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Falco',
    number: '20',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Marth',
    number: '21',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Lucina',
    number: '21e',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Young Link',
    number: '22',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ganondorf',
    number: '23',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Mewtwo',
    number: '24',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Roy',
    number: '25',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Chrom',
    number: '25e',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Mr. Game & Watch',
    number: '26',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Meta Knight',
    number: '27',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pit',
    number: '28',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Dark Pit',
    number: '28e',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Zero Suit Samus',
    number: '29',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Wario',
    number: '30',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Snake',
    number: '31',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ike',
    number: '32',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pokémon Trainer',
    number: '33',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pokémon Trainer',
    number: '34',
    pickable: false,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pokémon Trainer',
    number: '35',
    pickable: false,
    dlc: false,
    alts: [],
  },
  {
    name: 'Diddy Kong',
    number: '36',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Lucas',
    number: '37',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Sonic',
    number: '38',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'King Dedede',
    number: '39',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Olimar',
    number: '40',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Lucario',
    number: '41',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'R.O.B.',
    number: '42',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Toon Link',
    number: '43',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Wolf',
    number: '44',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Villager',
    number: '45',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Mega Man',
    number: '46',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Wii Fit Trainer',
    number: '47',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Rosalina & Luma',
    number: '48',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Little Mac',
    number: '49',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Greninja',
    number: '50',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Mii Brawler',
    number: '51',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Mii Swordfighter',
    number: '52',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Mii Gunner',
    number: '53',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Palutena',
    number: '54',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Pac-Man',
    number: '55',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Robin',
    number: '56',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Shulk',
    number: '57',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Bowser Jr.',
    number: '58',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Duck Hunt',
    number: '59',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ryu',
    number: '60',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ken',
    number: '60e',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Cloud',
    number: '61',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Corrin',
    number: '62',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Bayonetta',
    number: '63',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Inkling',
    number: '64',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Ridley',
    number: '65',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Simon',
    number: '66',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Richter',
    number: '66e',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'King K. Rool',
    number: '67',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Isabelle',
    number: '68',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Incineroar',
    number: '69',
    pickable: true,
    dlc: false,
    alts: [],
  },
  {
    name: 'Piranha Plant',
    number: '70',
    pickable: true,
    dlc: true,
    alts: [],
  },
  {
    name: 'Joker',
    number: '71',
    pickable: true,
    dlc: true,
    alts: [],
  },
];
